steps:
  - name: node
    entrypoint: yarn
    args: ['install']
  - name: node
    entrypoint: yarn
    args: ['test']
  - name: "gcr.io/cloud-builders/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}:$SHORT_SHA"
      - "-f"
      - "./docker/Dockerfile.production"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/${_NAMESPACE}:$SHORT_SHA"
  - name: "gcr.io/cloud-builders/kubectl"
    id: Deploy
    args:
      - "set"
      - "image"
      - "deploy"
      - "${_DEPLOY}"
      - "-n"
      - "${_NAMESPACE}"
      - "${_CONTAINER_NAME}=gcr.io/$PROJECT_ID/${_NAMESPACE}:$SHORT_SHA"
    waitFor: ["Build"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=${_ZONE}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}"